// simple call-insensitive field-sensitive points-to analysis in Datalog
.type Variable 
.type Allocation
.type Field

.decl assignAlloc(var:Variable, heap:Allocation)
.decl assign(source:Variable, destination:Variable) output
.decl primitiveAssign(source:Variable, dest:Variable)
.decl load(base:Variable, dest:Variable, field:Field)
.decl store(source:Variable, base:Variable, field:Field)
.decl varPointsTo(var:Variable, heap:Allocation) output
.decl alias(x:Variable,y:Variable) output

assign(Var1, Var2) :- primitiveAssign(Var1,Var2). 

alias(InstanceVar, IVar) :- varPointsTo(InstanceVar, InstanceHeap), varPointsTo(IVar, InstanceHeap).

varPointsTo(Var, Heap) :- assignAlloc(Var, Heap). 

varPointsTo(Var1, Heap) :- assign(Var2, Var1), varPointsTo(Var2, Heap).

assign(Var1, Var2) :- store(Var1, InstanceVar2, Field), alias(InstanceVar2, InstanceVar1), load(InstanceVar1, Var2, Field).

assignAlloc("v9", "h2").
assignAlloc("v7", "h4").
assignAlloc("v5", "h4").
assignAlloc("v2", "h0").
assignAlloc("v0", "h2").
assignAlloc("v3", "h3").
assignAlloc("v0", "h4").
assignAlloc("v7", "h0").
assignAlloc("v6", "h1").
assignAlloc("v5", "h1").
assignAlloc("v5", "h3").
assignAlloc("v2", "h1").
assignAlloc("v5", "h0").
assignAlloc("v3", "h1").
assignAlloc("v3", "h2").
assignAlloc("v5", "h3").
assignAlloc("v8", "h2").
assignAlloc("v6", "h2").
assignAlloc("v3", "h3").
assignAlloc("v2", "h4").
assignAlloc("v11", "h1").
assignAlloc("v11", "h0").
assignAlloc("v3", "h4").
assignAlloc("v1", "h3").
assignAlloc("v4", "h1").
assignAlloc("v8", "h3").
assignAlloc("v3", "h2").
assignAlloc("v10", "h4").
assignAlloc("v2", "h4").
assignAlloc("v4", "h3").
assignAlloc("v10", "h4").
assignAlloc("v3", "h3").
assignAlloc("v7", "h0").
assignAlloc("v2", "h4").
assignAlloc("v3", "h0").
assignAlloc("v3", "h0").
assignAlloc("v2", "h1").
assignAlloc("v4", "h4").
assignAlloc("v2", "h2").
assignAlloc("v4", "h4").
assignAlloc("v9", "h3").
assignAlloc("v11", "h2").
assignAlloc("v11", "h3").
assignAlloc("v1", "h0").
assignAlloc("v8", "h4").
assignAlloc("v5", "h0").
assignAlloc("v5", "h3").
assignAlloc("v11", "h3").
assignAlloc("v10", "h1").
assignAlloc("v7", "h1").
primitiveAssign("v6", "v0").
primitiveAssign("v1", "v5").
primitiveAssign("v2", "v7").
primitiveAssign("v4", "v11").
primitiveAssign("v8", "v7").
primitiveAssign("v2", "v2").
primitiveAssign("v3", "v7").
primitiveAssign("v1", "v10").
primitiveAssign("v11", "v8").
primitiveAssign("v9", "v8").
primitiveAssign("v7", "v0").
primitiveAssign("v11", "v0").
primitiveAssign("v11", "v7").
primitiveAssign("v5", "v2").
primitiveAssign("v4", "v6").
primitiveAssign("v5", "v5").
primitiveAssign("v11", "v7").
primitiveAssign("v11", "v8").
primitiveAssign("v1", "v5").
primitiveAssign("v2", "v9").
primitiveAssign("v5", "v8").
primitiveAssign("v5", "v1").
primitiveAssign("v8", "v9").
primitiveAssign("v1", "v8").
primitiveAssign("v11", "v0").
primitiveAssign("v2", "v10").
primitiveAssign("v7", "v7").
primitiveAssign("v7", "v9").
primitiveAssign("v7", "v0").
primitiveAssign("v9", "v6").
primitiveAssign("v10", "v0").
primitiveAssign("v1", "v4").
primitiveAssign("v6", "v4").
primitiveAssign("v1", "v4").
primitiveAssign("v5", "v10").
primitiveAssign("v2", "v8").
primitiveAssign("v3", "v11").
primitiveAssign("v11", "v10").
primitiveAssign("v5", "v2").
primitiveAssign("v7", "v1").
primitiveAssign("v7", "v11").
primitiveAssign("v2", "v3").
primitiveAssign("v8", "v10").
primitiveAssign("v7", "v11").
primitiveAssign("v1", "v6").
primitiveAssign("v11", "v2").
primitiveAssign("v10", "v11").
primitiveAssign("v10", "v4").
primitiveAssign("v7", "v11").
primitiveAssign("v0", "v8").
load("v1", "v0", "f5").
load("v11", "v4", "f8").
load("v0", "v10", "f9").
load("v5", "v1", "f8").
load("v3", "v8", "f5").
load("v0", "v2", "f5").
load("v11", "v2", "f9").
load("v7", "v9", "f3").
load("v10", "v9", "f2").
load("v6", "v6", "f9").
load("v9", "v8", "f2").
load("v3", "v3", "f6").
load("v3", "v5", "f2").
load("v1", "v2", "f3").
load("v3", "v9", "f4").
load("v2", "v3", "f4").
load("v6", "v1", "f2").
load("v10", "v0", "f4").
load("v10", "v11", "f2").
load("v2", "v6", "f7").
load("v1", "v11", "f1").
load("v1", "v9", "f6").
load("v7", "v2", "f6").
load("v4", "v10", "f5").
load("v2", "v1", "f1").
load("v7", "v7", "f8").
load("v8", "v1", "f6").
load("v6", "v4", "f4").
load("v10", "v0", "f2").
load("v5", "v5", "f7").
load("v8", "v7", "f9").
load("v9", "v7", "f2").
load("v1", "v5", "f0").
load("v2", "v0", "f0").
load("v0", "v10", "f8").
load("v11", "v9", "f5").
load("v11", "v5", "f8").
load("v2", "v4", "f4").
load("v1", "v6", "f8").
load("v5", "v5", "f4").
load("v6", "v10", "f9").
load("v5", "v11", "f9").
load("v10", "v2", "f5").
load("v10", "v3", "f6").
load("v6", "v2", "f7").
load("v0", "v10", "f8").
load("v8", "v11", "f3").
load("v11", "v6", "f9").
load("v10", "v11", "f5").
load("v8", "v10", "f4").
store("v8", "v0", "f7").
store("v1", "v8", "f6").
store("v1", "v2", "f7").
store("v0", "v11", "f1").
store("v6", "v3", "f2").
store("v8", "v3", "f8").
store("v7", "v9", "f6").
store("v10", "v10", "f3").
store("v7", "v6", "f2").
store("v1", "v5", "f4").
store("v8", "v7", "f0").
store("v3", "v0", "f5").
store("v8", "v7", "f7").
store("v3", "v5", "f1").
store("v8", "v3", "f4").
store("v3", "v10", "f5").
store("v6", "v11", "f8").
store("v3", "v3", "f0").
store("v5", "v11", "f3").
store("v0", "v1", "f6").
store("v4", "v3", "f4").
store("v0", "v7", "f0").
store("v11", "v8", "f4").
store("v5", "v6", "f0").
store("v7", "v4", "f2").
store("v11", "v11", "f2").
store("v4", "v0", "f3").
store("v0", "v0", "f0").
store("v4", "v6", "f9").
store("v11", "v9", "f0").
store("v3", "v0", "f8").
store("v11", "v9", "f3").
store("v5", "v1", "f3").
store("v8", "v3", "f6").
store("v0", "v2", "f2").
store("v3", "v5", "f9").
store("v9", "v5", "f0").
store("v4", "v10", "f5").
store("v0", "v2", "f6").
store("v10", "v11", "f0").
store("v10", "v5", "f8").
store("v11", "v0", "f7").
store("v3", "v9", "f5").
store("v6", "v10", "f8").
store("v7", "v8", "f4").
store("v6", "v11", "f6").
store("v4", "v7", "f3").
store("v4", "v8", "f3").
store("v2", "v10", "f1").
store("v8", "v11", "f1").
