name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:24.0

    steps:
    - uses: actions/checkout@v2
    - name: Copy Config
      run: mkdir -p _build/test/extras && cp -r config _build/test/extras/config
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct 
